# Generated by Django 4.2.4 on 2024-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_alter_mood_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='created_at',
            field=models.DateField(),
        ),
    ]
