# Generated by Django 4.2.4 on 2024-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_alter_mood_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mood',
            name='description',
        ),
        migrations.AlterField(
            model_name='mood',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
